const feedbackData = [
  {
    content: 'Great show',
    optIn: true,
    name: 'Sandra Dee',
    email: 'mymail@email.com',
    phone: '303-324-2343',
    updates: true,
    feedback: false,
    volunteer: true,
    timeStamp: 1543243785191,
    eventId: '444',
    feedbackId:'70', 
    didAnything:true,
  },
  {
    content: 'Fine',
    optIn: false,
    name: '',
    email: '',
    phone: '',
    updates: false,
    feedback: false,
    volunteer: false,
    timeStamp: 1543243785191,
    eventId: '444',
    feedbackId:'71', 
    didAnything:true,
  },
  {
    content: 'Quite liked what you were doing. There was all kinds of wonderful stuff going on!',
    optIn: true,
    name: 'Mark',
    email: 'mark@email.com',
    phone: '303-666-2343',
    updates: false,
    feedback: true,
    volunteer: true,
    timeStamp: 1543243785191,
    eventId: '444',
    feedbackId:'72', 
    didAnything:true,
  }
]

module.exports = { feedbackData }